import { ControlRun, QCIssue } from "./types.js";

export const SEED_CONTROL_RUNS: ControlRun[] = [
  { id: "R-EL-001", testName: "ELISA IgG", runDate: "2026-06-01", runNumber: 1, measuredValue: 1.52, expectedValue: 1.50, standardDeviation: 0.10, status: "In-Control", investigator: "Dr. Sarah Jenkins" },
  { id: "R-EL-002", testName: "ELISA IgG", runDate: "2026-06-02", runNumber: 2, measuredValue: 1.48, expectedValue: 1.50, standardDeviation: 0.10, status: "In-Control", investigator: "Dr. Sarah Jenkins" },
  { id: "R-EL-003", testName: "ELISA IgG", runDate: "2026-06-03", runNumber: 3, measuredValue: 1.55, expectedValue: 1.50, standardDeviation: 0.10, status: "In-Control", investigator: "Dr. Sarah Jenkins" },
  { id: "R-EL-004", testName: "ELISA IgG", runDate: "2026-06-04", runNumber: 4, measuredValue: 1.41, expectedValue: 1.50, standardDeviation: 0.10, status: "In-Control", investigator: "Emily Carter" },
  { id: "R-EL-005", testName: "ELISA IgG", runDate: "2026-06-05", runNumber: 5, measuredValue: 1.39, expectedValue: 1.50, standardDeviation: 0.10, status: "Warning", violationRules: ["1_2s (Value exceeds ±2SD warning)"], investigator: "Emily Carter" },
  { id: "R-EL-006", testName: "ELISA IgG", runDate: "2026-06-06", runNumber: 6, measuredValue: 1.38, expectedValue: 1.50, standardDeviation: 0.10, status: "In-Control", investigator: "Emily Carter" },
  { id: "R-EL-007", testName: "ELISA IgG", runDate: "2026-06-07", runNumber: 7, measuredValue: 1.45, expectedValue: 1.50, standardDeviation: 0.10, status: "In-Control", investigator: "Emily Carter" },
  { id: "R-EL-008", testName: "ELISA IgG", runDate: "2026-06-08", runNumber: 8, measuredValue: 1.37, expectedValue: 1.50, standardDeviation: 0.10, status: "In-Control", investigator: "Dr. Sarah Jenkins" },
  { id: "R-EL-009", testName: "ELISA IgG", runDate: "2026-06-09", runNumber: 9, measuredValue: 1.36, expectedValue: 1.50, standardDeviation: 0.10, status: "In-Control", investigator: "Dr. Sarah Jenkins" },
  { id: "R-EL-010", testName: "ELISA IgG", runDate: "2026-06-10", runNumber: 10, measuredValue: 1.35, expectedValue: 1.50, standardDeviation: 0.10, status: "In-Control", investigator: "Dr. Sarah Jenkins" },
  { id: "R-EL-011", testName: "ELISA IgG", runDate: "2026-06-11", runNumber: 11, measuredValue: 1.34, expectedValue: 1.50, standardDeviation: 0.10, status: "Out-of-Control", violationRules: ["10_X (Ten consecutive runs on one side of Mean)"], investigator: "Dr. Sarah Jenkins", notes: "Plate batch QC drift triggered a 10-X violation. Needs incubator check." },
  { id: "R-PC-001", testName: "RT-PCR Viral Load", runDate: "2026-06-10", runNumber: 1, measuredValue: 3.01, expectedValue: 3.00, standardDeviation: 0.20, status: "In-Control", investigator: "Dr. Kenji Tanaka" },
  { id: "R-PC-002", testName: "RT-PCR Viral Load", runDate: "2026-06-11", runNumber: 2, measuredValue: 2.95, expectedValue: 3.00, standardDeviation: 0.20, status: "In-Control", investigator: "Dr. Kenji Tanaka" },
  { id: "R-PC-003", testName: "RT-PCR Viral Load", runDate: "2026-06-12", runNumber: 3, measuredValue: 3.08, expectedValue: 3.00, standardDeviation: 0.20, status: "In-Control", investigator: "Emily Carter" },
  { id: "R-PC-004", testName: "RT-PCR Viral Load", runDate: "2026-06-13", runNumber: 4, measuredValue: 3.12, expectedValue: 3.00, standardDeviation: 0.20, status: "In-Control", investigator: "Emily Carter" },
  { id: "R-PC-005", testName: "RT-PCR Viral Load", runDate: "2026-06-14", runNumber: 5, measuredValue: 3.82, expectedValue: 3.00, standardDeviation: 0.20, status: "Out-of-Control", violationRules: ["1_3s (Value exceeds ±3SD limit)"], investigator: "Dr. Kenji Tanaka", notes: "Severe contamination suspected in the master mix template." },
  { id: "R-HP-001", testName: "HPLC Potency", runDate: "2026-06-05", runNumber: 1, measuredValue: 98.4, expectedValue: 98.50, standardDeviation: 0.80, status: "In-Control", investigator: "Dr. Sarah Jenkins" },
  { id: "R-HP-002", testName: "HPLC Potency", runDate: "2026-06-08", runNumber: 2, measuredValue: 98.6, expectedValue: 98.50, standardDeviation: 0.80, status: "In-Control", investigator: "Dr. Sarah Jenkins" },
  { id: "R-HP-003", testName: "HPLC Potency", runDate: "2026-06-10", runNumber: 3, measuredValue: 98.1, expectedValue: 98.50, standardDeviation: 0.80, status: "In-Control", investigator: "Dr. Sarah Jenkins" },
  { id: "R-HP-004", testName: "HPLC Potency", runDate: "2026-06-12", runNumber: 4, measuredValue: 97.2, expectedValue: 98.50, standardDeviation: 0.80, status: "In-Control", investigator: "Emily Carter" },
  { id: "R-HP-005", testName: "HPLC Potency", runDate: "2026-06-15", runNumber: 5, measuredValue: 95.8, expectedValue: 98.50, standardDeviation: 0.80, status: "Out-of-Control", violationRules: ["1_3s (Value exceeds ±3SD limit)"], investigator: "Dr. Sarah Jenkins", notes: "Column calibration shift. Retention index drifted. Calibrator replaced." },
];

export const SEED_QC_ISSUES: QCIssue[] = [
  {
    id: "QC-2026-001",
    sampleId: "SMP-HPLC-092",
    batchId: "BTH-HP-15",
    testName: "HPLC Potency",
    measuredValue: 95.8,
    expectedValue: 98.5,
    standardDeviation: 0.8,
    zScore: -3.375,
    priority: "Medium",
    status: "Resolved",
    investigator: "Dr. Sarah Jenkins",
    detectedAt: "2026-06-15T09:30:22Z",
    updatedAt: "2026-06-16T15:00:00Z",
    issueDescription: "HPLC potency benchmark dropped to 95.8% (expected 98.5% ± 0.8%), presenting a z-score of -3.38. This is a severe 1_3s Westgard limit violation, marking the analytical run as out-of-control.",
    rootCause: "Column particulate blockage and mobile phase aging led to abnormal peak broadening and low recovery.",
    capaActionPlan: "Flushed chromatographic column with 100% methanol overnight, prepared and validated fresh acetonitrile/water mobile phase, and re-calibrated index using a fresh reference standard.",
    aiAnalysis: "### Gemini Expert CAPA Analysis:\n- **Immediate Contamination Audit**: Standard peaks are broadened. Suspect column pressure increase. Please check column frit back-pressure.\n- **Recommended SOP Intervention**:\n  1. Isolate the batch immediately. Do not release clinical dosage.\n  2. Flush the reverse-phase column.\n  3. Verify flow rate stability to rule out pump seal wear.",
    comments: [
      { id: "c1", author: "Dr. Sarah Jenkins", text: "Successfully flushed column; post-wash calibration peaks look extremely sharp again.", createdAt: "2026-06-15T18:22:00Z" },
      { id: "c2", author: "Emily Carter", text: "Verified. Post-recalibration control sample returned a potency of 98.6%. Closing issue.", createdAt: "2026-06-16T14:50:00Z" },
    ],
    history: [
      { id: "h1", status: "Open", changedBy: "Dr. Sarah Jenkins", text: "QC issue auto-detected from HPLC Potency Run #5.", createdAt: "2026-06-15T09:30:22Z" },
      { id: "h2", status: "Under Investigation", changedBy: "Dr. Sarah Jenkins", text: "Investigation initiated. Pressure verified on HPLC System G.", createdAt: "2026-06-15T10:15:00Z" },
      { id: "h3", status: "Resolved", changedBy: "Dr. Sarah Jenkins", text: "Re-certified calibration run passed within acceptable ±1.5SD.", createdAt: "2026-06-16T15:00:00Z" },
    ],
  },
  {
    id: "QC-2026-002",
    sampleId: "SMP-PCR-449",
    batchId: "BTH-PC-08",
    testName: "RT-PCR Viral Load",
    measuredValue: 3.82,
    expectedValue: 3.00,
    standardDeviation: 0.20,
    zScore: 4.10,
    priority: "Urgent",
    status: "Under Investigation",
    investigator: "Dr. Kenji Tanaka",
    detectedAt: "2026-06-14T14:45:00Z",
    updatedAt: "2026-06-14T15:20:00Z",
    issueDescription: "Positive run control standard detected with viral amplification log value of 3.82 against target 3.00 ± 0.20 (Z-score = 4.1). Exceeds 1-3s Westgard limit, indicating a high-risk replication or template cross-contamination event.",
    rootCause: "",
    capaActionPlan: "",
    aiAnalysis: "### Gemini PCR Contamination Diagnostics:\n- **Westgard Pattern Detected**: Spike is isolated and extremely high (+4.1SD). Points to random contamination rather than systematic thermal cycler drift.\n- **Actionable CAPA Suggestions**:\n  1. Discard current master mix vial. Aliquots have likely been compromised by aerosol micro-particles during prep.\n  2. Execute UV decontamination protocol on Biosafety Cabinet Class II.\n  3. Recalibrate and run negative controls (NTC) in triplicate to guarantee absolute baseline clearance.",
    comments: [
      { id: "c11", author: "Dr. Kenji Tanaka", text: "Master mix aerosol contamination highly likely. Will run negative controls first thing tomorrow to inspect biosafety cabinet airflow.", createdAt: "2026-06-14T16:00:00Z" },
    ],
    history: [
      { id: "h11", status: "Open", changedBy: "Dr. Kenji Tanaka", text: "Auto-detected failure on positive standards RT-PCR run #5.", createdAt: "2026-06-14T14:45:00Z" },
      { id: "h12", status: "Under Investigation", changedBy: "Dr. Kenji Tanaka", text: "Assay isolated. No clinical patient results were processed or reported.", createdAt: "2026-06-14T15:20:00Z" },
    ],
  },
  {
    id: "QC-2026-003",
    sampleId: "SMP-EL-990",
    batchId: "BTH-EL-22",
    testName: "ELISA IgG",
    measuredValue: 1.34,
    expectedValue: 1.50,
    standardDeviation: 0.10,
    zScore: -1.60,
    priority: "Medium",
    status: "Open",
    investigator: "Emily Carter",
    detectedAt: "2026-06-11T11:15:00Z",
    updatedAt: "2026-06-11T12:00:00Z",
    issueDescription: "ELISA positive control returns 1.34, which mathematically is only -1.60SD from mean. However, 10 consecutive runs have fallen consistently below the mean of 1.50, constituting a 10_X Westgard systematic shift violation.",
    comments: [],
    history: [
      { id: "h31", status: "Open", changedBy: "Emily Carter", text: "QC issue generated due to systematic drift (10_X rule).", createdAt: "2026-06-11T11:15:00Z" },
    ],
  },
];
